Add env & input validation
PUP-BSIT/project-vrzn pull request #37
Opened 2023-12-30 05:42 UTC by Naoe-Adrian

Good Day team mates I add validation on transfer feature. On our next sprint I'll try to improve it more on account number. If account number does not exist in our database it will notify the user immediately.

![image](https://github.com/PUP-BSIT/project-vrzn/assets/115059074/01e06b99-85d8-49e3-ac17-c5f981952755)

![image](https://github.com/PUP-BSIT/project-vrzn/assets/115059074/84c3f3db-dfd6-4a45-bef5-03671f5ce82e)

2023-12-30 06:03 UTC, JheanKhendrick requested changes

2023-12-30 06:03 UTC, JheanKhendrick commented on app/bank_transfer/index.php
> +                        </div>
```suggestion
```

2023-12-30 06:03 UTC, JheanKhendrick commented on app/database/deposit.php
> +    }
```suggestion
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
```

2023-12-30 06:03 UTC, JheanKhendrick commented on app/database/funds-transfer.php
> +    }
```suggestion
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
```

2023-12-30 07:05 UTC, JheanKhendrick requested changes

2023-12-30 07:05 UTC, JheanKhendrick commented on app/database/get-acc-info.php
> +    }
```suggestion
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
```

2023-12-30 07:05 UTC, JheanKhendrick commented on app/database/send-otp-transfer.php
> +    }
```suggestion
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
```

2023-12-30 07:05 UTC, JheanKhendrick commented on app/database/send-otp-transfer.php
> +
```suggestion

```

2023-12-30 07:05 UTC, JheanKhendrick commented on app/database/transfer.php
> +    }
```suggestion
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
```

2023-12-30 07:05 UTC, JheanKhendrick commented on app/bank_transfer/bank_transfer.js
> +var bankSelector;
```suggestion
let transferTypeSelect;
let bankSelector;
```

2023-12-30 07:11 UTC, JheanKhendrick commented
Would it be possible for the frontend validation to behave consistently with the one implemented for the signup feature?

example:
![image](https://github.com/PUP-BSIT/project-vrzn/assets/96009163/44ea284d-8bf8-4648-bae9-a76957f9f230)

2023-12-30 11:15 UTC, Naoe-Adrian commented
Thank you, Jhean. I tried your method, but I'm having difficulty adding a border when the user inputs invalid values in the fields. Additionally, I've disabled the dropdown for the bank because users should not change it, the system automatically handles the exchange between internal and external transfers. 
![image](https://github.com/PUP-BSIT/project-vrzn/assets/115059074/f91fd848-bb6f-4d9a-9b47-58b380d3530a)


**_ON INTERNAL VALUE_**
![image](https://github.com/PUP-BSIT/project-vrzn/assets/115059074/d1748ee4-93bc-4733-86cc-3c15a83b0760)

**_ON EXTERNAL VALUE_**
![image](https://github.com/PUP-BSIT/project-vrzn/assets/115059074/abfd78cb-71ac-4989-9ee4-3b6d34ad7576)

2023-12-31 05:59 UTC, JohnStevenPenecitos approved these changes

2023-12-31 06:00 UTC, merged